### ISSUE TITLE
Error Cloning LLVM using Makefile (Permission Denied)

### ISSUE THREAD

**Issue by aaqdas** [pulp-platform/spatz#8]
I am encountering access error to the LLVM Repository when I run  `make all`

The error is as follows 

```shell
make[1]: Entering directory '/home/aqdas/spatz'
make[1]: '/home/aqdas/spatz/install/bender/bin/bender' is up to date.
make[1]: Leaving directory '/home/aqdas/spatz'
mkdir -p sw/toolchain
cd sw/toolchain && git clone git@github.com:pulp-platform/llvm-project.git
Cloning into 'llvm-project'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
make: *** [Makefile:37: sw/toolchain/llvm-project] Error 128
```

**Comment by micprog** [comment]
To solve this problem, either [add an ssh key to your github account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) or change the link in the Makefile line 37 from https://github.com/pulp-platform/spatz/blob/2dc5155edb6e27f6172fe549bf0987696edf7302/Makefile#L37
to:
```diff
	cd sw/toolchain && git clone https://github.com/pulp-platform/llvm-project.git
```

**Comment by aaqdas** [comment]
Thanks, it works now 💯
